### ISSUE TITLE
想要添加这个软件的快捷键指南 DaVinci Resolve

### ISSUE THREAD

**Issue by akio1321** [story-has-you/hotkey-cheatsheet-submit-apps#1]

**Comment by akio1321** [comment]
官网是这个https://www.blackmagicdesign.com/

**Comment by story-has-you** [comment]
@akio1321 您好，我已经整理对 davinci resolve软件整理了，点击：[Davinci Resolve](https://hotkeycheatsheet.com/app/davinci-resolve)
