### ISSUE TITLE
CorelDraw Keyboard Shortcuts

### ISSUE THREAD

**Issue by gitnobodynothing** [story-has-you/hotkey-cheatsheet-submit-apps#2]
[[## App official website
](https://learn.corel.com/wp-content/uploads/2022/03/CDGS2021-QuickReference-Shortcuts.pdf)](https://learn.corel.com/wp-content/uploads/2022/03/CDGS2021-QuickReference-Shortcuts.pdf)

**Comment by story-has-you** [comment]
Hello, the shortcut keys for CorelDraw have been sorted out. If it is helpful to you, you can promote it to the people around you, thank you.

[CorelDraw hotkeys](https://hotkeycheatsheet.com/en/hotkey-cheatsheet/corel-draw)
