### ISSUE TITLE
快捷键备忘录添加Dev C++快捷键

### ISSUE THREAD

**Issue by Evan0148** [story-has-you/hotkey-cheatsheet-submit-apps#3]
## App official website
您好！我想在快捷键备忘录中添加DevC++的快捷键
快捷键参考网站：https://blog.csdn.net/qq_44079145/article/details/105166545（Bing里搜的）

**Comment by story-has-you** [comment]
您好，Dev-C++ 已经整理好了，可以直接访问：[Dev-C++](https://hotkeycheatsheet.com/hotkey-cheatsheet/dev-c)
